import Modal from "@/components/custom/Modal";
import { useState } from "react";
import ISelect from "@/components/custom/Select";
import { useCreateEmployee, useUpdateEmployee, useDeleteEmployee } from "@/queries/employeeQueries";

export default function StaffModal({ isOpen, onClose, mode = 'add', staffData = null }) {
  const [name, setName] = useState(staffData?.name || "");
  const [selectedRole, setSelectedRole] = useState(staffData?.employee_type?.name?.toLowerCase().replace(" ", "-") || "head-chef");
  const [selectedStatus, setSelectedStatus] = useState(staffData?.active ? "active" : "inactive" || "active");
  const [contactInfo, setContactInfo] = useState(staffData?.email || "");

  const createEmployeeMutation = useCreateEmployee();
  const updateEmployeeMutation = useUpdateEmployee();
  const deleteEmployeeMutation = useDeleteEmployee();

  const roleOptions = [
    { value: "head-chef", label: "Head Chef" },
    { value: "assistant-chef", label: "Assistant Chef" },
    { value: "sushi-chef", label: "Sushi Chef" },
    { value: "waitress", label: "Waitress" },
  ];

  const statusOptions = [
    { value: "active", label: "Active" },
    { value: "inactive", label: "Inactive" },
  ];

  const handleSave = async () => {
    try {
      if (mode === 'delete') {
        await deleteEmployeeMutation.mutateAsync({ 
          id: staffData?.id, 
          name: staffData?.name 
        });
      } else if (mode === 'edit') {
        await updateEmployeeMutation.mutateAsync({ 
          id: staffData?.id, 
          data: { 
            name, 
            employee_type_id: selectedRole === 'head-chef' ? 1 : selectedRole === 'assistant-chef' ? 2 : selectedRole === 'sushi-chef' ? 3 : 4,
            active: selectedStatus === 'active', 
            email: contactInfo 
          } 
        });
      } else {
        await createEmployeeMutation.mutateAsync({ 
          name, 
          employee_type_id: selectedRole === 'head-chef' ? 1 : selectedRole === 'assistant-chef' ? 2 : selectedRole === 'sushi-chef' ? 3 : 4,
          active: selectedStatus === 'active', 
          email: contactInfo 
        });
      }
      onClose(); 
    } catch (error) {
      console.error('Error:', error);
    }
  };

  const selectTriggerClass = "rounded-lg border-gray-200 bg-primary px-3 text-sm font-normal text-white [&_svg]:!text-white [&_svg]:!opacity-100";
  const selectContentClass = "[&_svg]:!text-white [&_svg]:!opacity-100";

  return (
    <Modal
      isOpen={isOpen}
      onClose={onClose}
      title={mode === 'add' ? 'Add New Employee' : mode === 'edit' ? 'Edit Employee' : 'Delete Employee'}
      description={mode === 'add' ? 'Enter the details of the new staff member below.' : mode === 'edit' ? 'Update the staff member details below.' : 'Are you sure you want to delete this staff member?'}
      size="default" // You can change this to "lg" or "xl" based on your sizeClasses
      isLoading={createEmployeeMutation.isPending || 
                   updateEmployeeMutation.isPending || 
                   deleteEmployeeMutation.isPending}
      loadingText={mode === 'delete' ? 'Deleting...' : 'Saving...'}
      primaryAction={{
        label: mode === 'add' ? 'Save Employee' : mode === 'edit' ? 'Update Employee' : 'Delete Employee',
        onConfirm: handleSave,
        autoClose: false // Set to false so we can handle the close manually after the fake API call
      }}
      secondaryAction={{
        label: "Cancel",
        onCancel: onClose
      }}
    >
      {/* Just put your form fields in the children. 
        The footer and buttons are automatically generated by your custom Modal!
      */}
      <div className="flex flex-col gap-4">
        {mode === 'delete' ? (
          <div className="text-center py-4">
            <p className="text-gray-600">Are you sure you want to delete <strong>{staffData?.name}</strong>?</p>
            <p className="text-sm text-gray-500 mt-2">This action cannot be undone.</p>
          </div>
        ) : (
          <>
            <div className="flex flex-col gap-1.5">
              <label className="text-sm font-medium text-gray-700">Full Name</label>
              <input 
                placeholder="e.g. John Doe" 
                value={name} 
                onChange={(e) => setName(e.target.value)} 
                className="flex h-10 w-full rounded-md border border-gray-200 bg-white px-3 py-2 text-sm"
              />
            </div>
            
            <div className="flex flex-col gap-1.5">
              <label className="text-sm font-medium text-gray-700">Role</label>
              <ISelect 
                useForm={false}
                showAll={false}
                placeholder="e.g. Head Chef" 
                value={selectedRole}
                options={roleOptions}
                onValueChange={(option) => setSelectedRole(option?.value ?? "head-chef")}
                triggerClassName={selectTriggerClass}
                contentClassName={selectContentClass}
              />
            </div>

            <div className="flex flex-col gap-1.5">
              <label className="text-sm font-medium text-gray-700">Contact Info</label>
              <input 
                placeholder="e.g. johndoe@gmail.com" 
                value={contactInfo} 
                onChange={(e) => setContactInfo(e.target.value)} 
                className="flex h-10 w-full rounded-md border border-gray-200 bg-white px-3 py-2 text-sm"
              />
            </div>

            {/* <div className="flex flex-col gap-1.5">
              <label className="text-sm font-medium text-gray-700">Status</label>
              <ISelect 
                useForm={false}
                showAll={false}
                placeholder="e.g. Active" 
                value={selectedStatus}
                options={statusOptions}
                onValueChange={(option) => setSelectedStatus(option?.value ?? "active")}
                triggerClassName={selectTriggerClass}
                contentClassName={selectContentClass}
              />
            </div> */}
          </>
        )}
      </div>
    </Modal>
  );
}